dependencies:
  - alias: operator
    name: entando-k8s-controller-coordinator
    repository: file://./tmp/entando-k8s-controller-coordinator/charts/entando-k8s-controller-coordinator
    version: 7.0.0-ENG-3143-PR-91
    #condition: bundle.olmDisabled
