dependencies:
  - alias: operator
    name: entando-k8s-controller-coordinator
    repository: file://./tmp/entando-k8s-controller-coordinator/charts/entando-k8s-controller-coordinator
    version: 7.0.3-ENG-3686-PR-103
    #condition: bundle.olmDisabled
