dependencies:
  - alias: operator
    name: entando-k8s-controller-coordinator
    repository: file://./tmp/entando-k8s-controller-coordinator/charts/entando-k8s-controller-coordinator
    version: 7.2.0-ENG-4701-PR-126
    #condition: bundle.olmDisabled
