dependencies:
  - alias: operator
    name: entando-k8s-controller-coordinator
#    repository: file://../entando-k8s-controller-coordinator/charts/entando-k8s-controller-coordinator
    condition: bundle.olmDisabled
    repository: https://chartmuseum-jx.apps.serv.run
    version: 6.4.0
