apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: entando/entando-k8s-operator-bundle
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
  - name: community
    build:
      artifacts:
        - image: entando/entando-k8s-operator-bundle-community
          docker:
            dockerfile: Dockerfile.community
  - name: rh-cert
    build:
      artifacts:
        - image: entando/entando-k8s-operator-bundle
          docker:
            dockerfile: Dockerfile.rh-cert
