apiVersion: v1
kind: ConfigMap
metadata:
  name: example-entando-operator-config
data:
  default.routing.suffix: apps.enta-azure-ocp47.entazure.com
  pod.readiness.timeout.seconds: "1200"
  pod.completion.timeout.seconds: "1200"
  pod.shutdown.timeout.seconds: "600"
  image.pull.secrets: entando-pull-secret
  disable.keycloak.ssl.requirement: "true"
  force.db.password.reset: "false"
  disable.pvc.garbage.collection: "false"
  use.auto.cert.generation: "true"