---
# Source: entando-k8s-operator-bundle/charts/operator/templates/entando-empty-tls-secret.yaml
apiVersion: v1
stringData:
  tls.crt: ''
  tls.key: ''
kind: Secret
metadata:
  name: entando-empty-tls-secret
type: kubernetes.io/tls

---
# Source: entando-k8s-operator-bundle/charts/operator/templates/docker-image-info-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: entando-docker-image-info
data:
  app-builder: >-
    {"version":"6.3.93","executable-type":"n/a","registry":"docker.io","organization":"entando"}
  busybox: >-
    {"version":"latest","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-avatar-plugin: >-
    {"version":"6.0.5","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-component-manager: >-
    {"version":"6.3.26","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-de-app-eap: >-
    {"version":"6.3.68","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-de-app-wildfly: >-
    {"version":"6.3.68","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-app-controller: >-
    {"version":"0.0.0-SNAPSHOT-PR-32-47","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-app-plugin-link-controller: >-
    {"version":"0.0.0-SNAPSHOT-PR-15-15","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-database-service-controller: >-
    {"version":"0.0.0-SNAPSHOT-PR-10-21","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-dbjob: >-
    {"version":"6.3.8","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-keycloak-controller: >-
    {"version":"0.0.0-SNAPSHOT-PR-28-30","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-plugin-controller: >-
    {"version":"0.0.0-SNAPSHOT-PR-27-21","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-service: >-
    {"version":"0.0.0-SNAPSHOT-4","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-keycloak: >-
    {"version":"6.3.9","executable-type":"","registry":"docker.io","organization":"entando"}
  entando-process-driven-plugin: >-
    {"version":"6.0.50","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-redhat-sso: >-
    {"version":"6.3.9","executable-type":"","registry":"docker.io","organization":"entando"}
  mysql-80-centos7: >-
    {"version":"latest","executable-type":"jvm","registry":"docker.io","organization":"centos"}
  postgresql-12-centos7: >-
    {"version":"latest","executable-type":"jvm","registry":"docker.io","organization":"centos"}
  rhel8-mysql-80: >-
    {"version":"latest","executable-type":"jvm","registry":"registry.redhat.io","organization":"rhel8"}
  rhel8-postgresql-12: >-
    {"version":"latest","executable-type":"jvm","registry":"registry.redhat.io","organization":"rhel8"}

---
# Source: entando-k8s-operator-bundle/charts/operator/templates/operator-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: entando-operator
imagePullSecrets:
  - name: redhat-registry
  - name: entando-pull-secret

---
# Source: entando-k8s-operator-bundle/charts/operator/templates/plugin-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: entando-plugin
imagePullSecrets:
  - name: redhat-registry
  - name: entando-pull-secret

---
# Source: entando-k8s-operator-bundle/charts/operator/templates/operator-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: entando-operator
rules:
  - apiGroups:
      - entando.org
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - configmaps
      - serviceaccounts
      - events
    verbs:
      - "*"
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods/exec
    verbs:
      - get
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - get
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - get
      - create
  - apiGroups:
      - route.openshift.io
    resources:
      - "routes"
      - "routes/custom-host"
    verbs:
      - "*"

---
# Source: entando-k8s-operator-bundle/charts/operator/templates/plugin-role.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: entando-plugin
rules:
  - apiGroups:
      - entando.org
    resources:
      - entandoplugins
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - delete
      - update

---
# Source: entando-k8s-operator-bundle/charts/operator/templates/pod-viewer-role.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-viewer
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - "list"
      - "get"
      - "watch"
---
# Source: entando-k8s-operator-bundle/charts/operator/templates/default-pod-viewer-rolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-pod-viewer-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-viewer
subjects:
  - kind: ServiceAccount
    name: default
---
# Source: entando-k8s-operator-bundle/charts/operator/templates/operator-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: entando-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: entando-operator
subjects:
  - kind: ServiceAccount
    name: entando-operator

---
# Source: entando-k8s-operator-bundle/charts/operator/templates/plugin-rolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: entando-plugin-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: entando-plugin
subjects:
  - kind: ServiceAccount
    name: entando-plugin

---
# Source: entando-k8s-operator-bundle/charts/operator/templates/entando-k8s-service-service.yaml
kind: Service
apiVersion: v1
metadata:
  name: entando-k8s-service
spec:
  ports:
    - name: k8s-svc-port
      protocol: TCP
      port: 8084
      targetPort: 8084
  selector:
    deployment: entando-k8s-service

---
# Source: entando-k8s-operator-bundle/templates/entando-k8s-service-service.yaml
kind: Service
apiVersion: v1
metadata:
  name: entando-k8s-service
spec:
  ports:
    - name: k8s-svc-port
      protocol: TCP
      port: 8084
      targetPort: 8084
  selector:
    k8s-app: entando-k8s-service

---
# Source: entando-k8s-operator-bundle/charts/operator/templates/deployment.yaml
apiVersion: "extensions/v1beta1"
kind: Deployment
metadata:
  name: entando-operator
  labels:
    draft: draft-app
    chart: "operator-0.0.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      draft: draft-app
      app: entando-operator
  template:
    metadata:
      labels:
        draft: draft-app
        app: entando-operator
    spec:
      serviceAccountName: entando-operator
      volumes:
      containers:
        - name: operator
          image: "entando/entando-k8s-controller-coordinator:0.0.0-SNAPSHOT-10"
          imagePullPolicy: Always
          volumeMounts:
          env:
            - name: ENTANDO_K8S_OPERATOR_SERVICEACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: ENTANDO_K8S_OPERATOR_SECURITY_MODE
              value: "strict"
          livenessProbe:
            exec:
              command:
                - cat
                - /tmp/EntandoControllerCoordinator.ready
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/EntandoControllerCoordinator.ready
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 400m
              memory: 512Mi
          terminationGracePeriodSeconds: 

---
# Source: entando-k8s-operator-bundle/charts/operator/templates/entando-k8s-service-deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: entando-k8s-service
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: entando-k8s-service
  template:
    metadata:
      name: entando-k8s-service-pod
      labels:
        deployment: entando-k8s-service
    spec:
      restartPolicy: Always
      serviceAccountName: entando-operator
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 768Mi
            requests:
              cpu: 250m
              memory: 192Mi
          name: k8s-svc-container
          env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /k8s
          ports:
            - name: k8s-svc-port
              containerPort: 8084
              protocol: TCP
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /k8s/actuator/health
              port: 8084
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /k8s/actuator/health
              port: 8084
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          image: >-
            docker.io/entando/entando-k8s-service:0.0.0-SNAPSHOT-4
      serviceAccount: entando-operator

---
# Source: entando-k8s-operator-bundle/charts/operator/templates/entando-editor-clusterrole.yaml

---
# Source: entando-k8s-operator-bundle/charts/operator/templates/ingress-viewer-clusterrole.yaml

---
# Source: entando-k8s-operator-bundle/charts/operator/templates/operator-clusterrole.yaml


---
# Source: entando-k8s-operator-bundle/charts/operator/templates/operator-clusterrolebinding.yaml

---
# Source: entando-k8s-operator-bundle/charts/operator/templates/operator-pod-viewer-clusterrolebinding.yaml

---
# Source: entando-k8s-operator-bundle/charts/operator/templates/pod-viewer-clusterrole.yaml

---
# Source: entando-k8s-operator-bundle/templates/docker-image-info-configmap.yaml

---
# Source: entando-k8s-operator-bundle/templates/entando-empty-tls-secret.yaml

---
# Source: entando-k8s-operator-bundle/templates/entando-k8s-operator.v6.3.x.clusterserviceversion.yaml

