kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: entando-crd-viewer
  labels:
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - entandoapppluginlinks.entando.org
      - entandoapps.entando.org
      - entandodatabaseservices.entando.org
      - entandodebundles.entando.org
      - entandokeycloakservers.entando.org
      - entandoplugins.entando.org
      - providedcapabilities.entando.org
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: entando-crd-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: entando-crd-viewer
subjects:
  - kind: Group
    name: system:serviceaccounts
