kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: entando-viewer
  labels:
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups:
      - entando.org
    resources:
      - "*"
    verbs:
      - "get"
      - "list"
      - "watch"
