name: Entando Release

on:
  repository_dispatch:
    types: [entando-release]

env:
  # URL of the DockerHub repositories configuration file
  DOCKER_HUB_REPOS_CONFIG_URL: global-config/docker-hub-repositories.json
  # GitHub token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Major release version specified in the repository_dispatch payload
  MAJOR: ${{ github.event.client_payload.major }}
  # Minor release version specified in the repository_dispatch payload
  MINOR: ${{ github.event.client_payload.minor }}
  # Patch release version specified in the repository_dispatch payload
  PATCH: ${{ github.event.client_payload.patch }}
  # Suffix release version specified in the repository_dispatch payload
  SUFFIX: ${{ github.event.client_payload.suffix }}

  # Auxiliary variables that are created based in the repository_dispatch payload
  # Release version. Example: 7.1
  RELEASE_VERSION: ${{ github.event.client_payload.major }}.${{ github.event.client_payload.minor }}
  # Release version with patch. Example: 7.1.4
  RELEASE_VERSION_PATCH: ${{ github.event.client_payload.major }}.${{ github.event.client_payload.minor }}.${{ github.event.client_payload.patch }}
  # Base branch. Example: release/7.1
  BASE_BRANCH: release/${{ github.event.client_payload.major }}.${{ github.event.client_payload.minor }}
  # Release branch. Example: 7.1.4-rc2
  RELEASE_BRANCH: ${{ github.event.client_payload.major }}.${{ github.event.client_payload.minor }}.${{ github.event.client_payload.patch }}${{ github.event.client_payload.suffix }}
  # Release tag. Example: v7.1.4-rc2
  RELEASE_TAG: v${{ github.event.client_payload.major }}.${{ github.event.client_payload.minor }}.${{ github.event.client_payload.patch }}${{ github.event.client_payload.suffix }}

jobs:
  update-operator-bundle-values:
    name: Update values.yaml
    runs-on: ubuntu-latest
    steps:
    
    # Checkout the catalyst-infra-templates repository
    - name: Checkout catalyst-infra-templates
      uses: actions/checkout@v3
      with:
        repository: entando/catalyst-infra-templates
        
    # Load Docker Hub repositories configuration
    - name: Load Docker Hub repositories
      run: |
        echo "DOCKER_HUB_REPOS=$(jq -c . < $DOCKER_HUB_REPOS_CONFIG_URL)" >> $GITHUB_ENV

    # Checkout the entando-k8s-operator-bundle repository
    - name: Checkout entando-k8s-operator-bundle
      uses: actions/checkout@v3
      with:
        ref: ${{ env.BASE_BRANCH }}
        fetch-depth: 0
        
    # Validate the release tag and branch variables
    - name: Validate payload
      run: |
        echo "Checking if release tag: $RELEASE_TAG already exists"
        # Check if the release tag already exists
        if [[ $(git tag -l $RELEASE_TAG) ]]
        then
            echo "::error :: Tag '$RELEASE_TAG' already exists"
            exit 1
        fi
        
        # Check if the release branch already exists
        if [[ "$(git ls-remote | grep refs/heads/$RELEASE_BRANCH)" ]]
        then
            echo "::error :: Branch '$RELEASE_BRANCH' already exists"
            exit 2
        fi
       
    # Create the release branch
    - name: Create release branch
      run: |
        git checkout -b $RELEASE_BRANCH
        
    # Update images versions and SHA digests in the values.yaml file
    - name: Set images versions and sha
      env: 
        # Convert the client_payload JSON object to a string and set it as an environment variable
        CLIENT_PAYLOAD: ${{ toJson(github.event.client_payload) }}
      run: |
        for IMAGE in $(echo "$CLIENT_PAYLOAD" | jq -c '.images[]'); do
          IMAGE_NAME=$(echo $IMAGE | jq -r '.name')
          NEW_VERSION=$(echo $IMAGE | jq -r '.version')
          FOUND_IMAGE=false
          FOUND_VERSION=false
          for DOCKER_HUB_REPO in $(echo "$DOCKER_HUB_REPOS" | jq -c '.images[]'); do
            REPO_NAME=$(echo $DOCKER_HUB_REPO | jq -r '.name')
            REPO_NAMESPACE=$(echo $DOCKER_HUB_REPO | jq -r '.docker_hub_namespace')
            REPO=$(echo $DOCKER_HUB_REPO | jq -r '.docker_hub_repository')
            if [[ $IMAGE_NAME == $REPO_NAME ]]
            then 
              FOUND_IMAGE=true
              BASE_URL="https://hub.docker.com/v2/namespaces/$REPO_NAMESPACE/repositories/$REPO/tags?name="$NEW_VERSION"&page_size=1000"
              echo "Querying docker hub: $BASE_URL"
              curl -X GET $BASE_URL > result.json
              COUNT=$(jq .count result.json)
              # Check if the Docker image version exists on Docker Hub
              if [[ $COUNT > 0 ]]
              then
                for ((i=0;i<COUNT;i++)); do
                  DOCKER_HUB_VERSION=$(jq .results[$i].name result.json)
                  if [[ '"'$NEW_VERSION'"' == $DOCKER_HUB_VERSION ]]
                  then
                     FOUND_VERSION=true
                     ORIGINAL_VERSION=$(yq ".operator.relatedImages.$IMAGE_NAME.version" values.yaml)
                     ORIGINAL_SHA=$(yq ".operator.relatedImages.$IMAGE_NAME.sha256" values.yaml)
                     SHA=$(jq .results[$i].images[0].digest result.json)
                     SHA=${SHA//sha256:/}
                     # Update the version and SHA digest of the Docker image in the values.yaml file
                     yq -i ".operator.relatedImages.$IMAGE_NAME.version = $DOCKER_HUB_VERSION" values.yaml
                     yq -i ".operator.relatedImages.$IMAGE_NAME.sha256 = $SHA" values.yaml
                     # Print the original and updated version and SHA digest of the Docker image
                     echo "Updating values.yaml"
                     echo "Image name: $IMAGE_NAME"
                     echo 'Original data: version="'$ORIGINAL_VERSION'", sha="'$ORIGINAL_SHA'"'
                     echo 'New data: version="'$NEW_VERSION'", sha='$SHA
                     echo ""
                     break
                  fi
                done
              fi
              # If the Docker image version doesn't exist on Docker Hub, exit with an error
              if [[ $FOUND_VERSION = false ]]
              then
                echo "::error :: Version '$NEW_VERSION' does not exist for '$IMAGE_NAME'"
                exit 3
              fi
            fi
          done
          # If the Docker image doesn't exist in the Docker Hub repositories configuration, exit with an error
          if [[ $FOUND_IMAGE = false ]]
          then
            echo "::error :: Image '$IMAGE_NAME' does not exist in '$DOCKER_HUB_REPOS_CONFIG_URL'"
            exit 4
          fi
        done
        
    # Commit the changes to Git
    - name: Commit in branch
      run: |
        git config --global user.name 'Entando GitHub Actions'
        git config --global user.email 'github-actions@entando.com'
        git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        git add values.yaml
        git commit -m "Automated values.yaml update"
        git push --set-upstream origin $RELEASE_BRANCH
        
  update-manifest-files:
    name: Update manifest files
    runs-on: ubuntu-latest
    needs: update-operator-bundle-values
    steps:
    
    # Checkout the entando-k8s-operator-bundle repository
    - name: Checkout entando-k8s-operator-bundle
      uses: actions/checkout@v3
      with:
        ref: ${{ env.RELEASE_BRANCH }}
        
    # Generating manifest files
    - name: Run generate-manifest.sh
      run: |
        bash ./generate-manifests.sh --version "${{ env.RELEASE_VERSION_PATCH }}" --mainline "${{ env.RELEASE_VERSION }}"
        
    # Commit the changes to Git
    - name: Commit in branch
      run: |
        git config --global user.name 'Entando GitHub Actions'
        git config --global user.email 'github-actions@entando.com'
        git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        git add -A
        git commit -m "Automated manifest files update"
        git push --set-upstream origin $RELEASE_BRANCH
