name: RELEASE

on:
  repository_dispatch:
    types: [release-entando]

jobs:
  download-operator-bundle:
    name: Download entando-k8s-operator-bundle
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
          ref: develop
    - name: Echo payload
      run: |
        echo '${{ toJSON(github.event.client_payload) }}'
    - name: Run script
      run: |
        echo "rhel8_mysql_80: sha = ${{ github.event.client_payload.relatedImages.rhel8_mysql_80.sha }}, version = ${{ github.event.client_payload.relatedImages.rhel8_mysql_80.version }}"
        echo "rhel8_postgresql_12: sha = ${{ github.event.client_payload.relatedImages.rhel8_postgresql_12.sha }}, version = ${{ github.event.client_payload.relatedImages.rhel8_postgresql_12.version }}"