name: RELEASE

on:
  workflow_dispatch:
    inputs:
      - name: param1
        description: 'The first parameter'
        required: true
      - name: param2
        description: 'The second parameter'
        required: false

jobs:
  download-operator-bundle:
    name: Download entando-k8s-operator-bundle
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          ref: develop
    - name: Run script
      run: |
        echo "Running script..."
        echo "Param1 value: ${{ inputs.param1 }}"
        echo "Param2 value: ${{ inputs.param2 }}"